### ISSUE TITLE
cp0 prid reg not implemented

### ISSUE THREAD

**Issue by clbr** [n64dev/cen64#174]
The PRID register of the main core's cp0 should be a read-only reg showing the processor's type and revision. cen64 currently doesn't implement it and returns 0.

**Comment by clbr** [comment]
My NTSC charcoal gray unit reports 0xb22, aka vr4300, revision 2.2.

Test rom:
https://github.com/clbr/n64prid

**Comment by sp1187** [comment]
Most console revisions have 0xB22, though some very early consoles have 0xB10 (these have the mulmul bug which is possibly very tricky to emulate), therefore 0xB22 should be the proper value to implement here.

**Comment by clbr** [comment]
Same applies for cp1 prid aka fcr0, the FPU's revision register. sp1187, do you have the common values for that so I don't have to test mine?

**Comment by clbr** [comment]
Curious, my fpid is 0xa00, even though the vr4300 manual says the impl part should be 0xb.

**Comment by clbr** [comment]
https://gist.github.com/murachue/531ed3ca201ab4155d22442272d92ed2#file-201902140007-txt
Well, even 0xb10 consoles have a 0xa00 fpu.

**Comment by sp1187** [comment]
Fixed by #179.

**Comment by clbr** [comment]
Only partially fixed, the fpu prid is not yet implemented. Please reopen.
